### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/histoslider

### ISSUE THREAD

**Issue by trivektor** [samhogg/histoslider#34]
## Tris-MBP:aggd_configuration_portal_new trivuong$ npm install --save histoslider

npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "histoslider"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/histoslider
npm ERR! 404
npm ERR! 404 'histoslider' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by samhogg** [comment]
Hey! Yeah I should get around to polishing this and publishing it - will aim to have a go later this week.
